services:
    nginx:
        image: nginx:latest
        container_name: em-nginx
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./resource/html:/usr/share/nginx/html
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        depends_on:
            - certbot
        restart: always

    certbot:
        image: certbot/certbot
        container_name: em-certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew --webroot -w /var/www/certbot --quiet && docker exec em-nginx nginx -s reload; done'"

    # PostgreSQL 배포용 컨테이너
    postgresql_deploy:
        image: postgres:latest
        container_name: em-postgresql-deploy
        ports:
            - '${POSTGRES_PORT_DEPLOY}:5434'
        environment:
            POSTGRES_DB: ${POSTGRES_DB_DEPLOY}
            POSTGRES_USER: ${POSTGRES_USER_DEPLOY}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEPLOY}
        volumes:
            - ./data/postgres_deploy:/var/lib/postgresql/data

    # PostgreSQL 개발용 컨테이너
    postgresql_dev:
        image: postgres:latest
        container_name: em-postgresql-dev
        ports:
            - '${POSTGRES_PORT_DEV}:5432'
        environment:
            POSTGRES_DB: ${POSTGRES_DB_DEV}
            POSTGRES_USER: ${POSTGRES_USER_DEV}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_DEV}
        volumes:
            - ./data/postgres_dev:/var/lib/postgresql/data

    # PostgreSQL 테스트용 컨테이너
    postgresql_test:
        image: postgres:latest
        container_name: em-postgresql-test
        ports:
            - '${POSTGRES_PORT_TEST}:5433'
        environment:
            POSTGRES_DB: ${POSTGRES_DB_TEST}
            POSTGRES_USER: ${POSTGRES_USER_TEST}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
        volumes:
            - ./data/postgres_test:/var/lib/postgresql/data

    # Redis 배포용 컨테이너
    redis_deploy:
        image: redis:latest
        container_name: em-redis-deploy
        ports:
            - '${REDIS_PORT_DEPLOY}:6381'
        command: redis-server --requirepass ${REDIS_PASSWORD_DEPLOY}
        volumes:
            - ./data/redis_deploy:/data

    # Redis 개발용 컨테이너
    redis_dev:
        image: redis:latest
        container_name: em-redis-dev
        ports:
            - '${REDIS_PORT_DEV}:6379'
        command: redis-server --requirepass ${REDIS_PASSWORD_DEV}
        volumes:
            - ./data/redis_dev:/data

    # Redis 테스트용 컨테이너
    redis_test:
        image: redis:latest
        container_name: em-redis-test
        ports:
            - '${REDIS_PORT_TEST}:6380'
        command: redis-server --requirepass ${REDIS_PASSWORD_TEST}
        volumes:
            - ./data/redis_test:/data
